[package]
name = "storage-report"
version = "0.1.0"
authors = ["silver"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://ipfssearch.io"

[dependencies]
# third party dependencies
codec = { default-features = false, package = 'parity-scale-codec', version = '1.3.4' }
serde = { optional = true, version = '1.0.106' }
serde_json = "1.0.55"
signatory = "0.20.0"
signatory-ring = "0.20.0"
hex = '0.4.2'
base64 = "0.12.2"
openssl = { optional = true, version = "0.10.29" }

# substrate frame dependencies
frame-support = { default-features = false, version = '2.0.0-rc6' }
frame-system = { default-features = false, version = '2.0.0-rc6' }

# substrate primitives
sp-core = { default-features = false, version = '2.0.0-rc6' }
sp-io = { default-features = false, version = '2.0.0-rc6' }
sp-runtime = { default-features = false, version = '2.0.0-rc6' }
sp-runtime-interface = { default-features = false, version = '2.0.0-rc6' }
sp-std = { default-features = false, version = '2.0.0-rc6' }


[dev-dependencies]
keyring = { package = "sp-keyring", version = '2.0.0-rc6' }
frame-benchmarking = { version = '2.0.0-rc6' }

[features]
default = ['std']
std = [
    'serde',
    'openssl',
    'codec/std',
    'frame-support/std',
    'sp-core/std',
    'sp-io/std',
    'sp-runtime/std',
    'sp-std/std',
    'frame-system/std',
    'sp-runtime-interface/std',
    'primitives/std'
]
runtime-benchmarks = [
    "frame-benchmarking",
]